/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiprojectoct2024;

import javax.swing.JOptionPane;

/**
 *
 * @author Othman Family
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLblName = new javax.swing.JLabel();
        jPanelPlate = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLblPrice1 = new javax.swing.JLabel();
        jLblPrice2 = new javax.swing.JLabel();
        jLblPrice3 = new javax.swing.JLabel();
        jPanelReceipt = new javax.swing.JPanel();
        jLblTotal = new javax.swing.JLabel();
        jLblServTax = new javax.swing.JLabel();
        jLblGovTax = new javax.swing.JLabel();
        jLblAmount = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jTxtServTax = new javax.swing.JTextField();
        jTxtGovTax = new javax.swing.JTextField();
        jTxtAmount = new javax.swing.JTextField();
        jLblQty = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jBtnCalc = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant");
        setBackground(new java.awt.Color(102, 167, 252));

        jLblName.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLblName.setText("WESTERN EXOTIC RESTAURANT");

        jPanelPlate.setBackground(new java.awt.Color(255, 255, 204));
        jPanelPlate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)), "Main Plate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Small", 0, 12), new java.awt.Color(102, 0, 0))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton1.setText("Teriyaki");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton2.setText("Pan Fried Fish");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton3.setText("BBQ Lamb Chop");

        jLblPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPrice1.setText("RM 29.90");

        jLblPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPrice2.setText("RM 34.00");

        jLblPrice3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPrice3.setText("RM 32.90");

        javax.swing.GroupLayout jPanelPlateLayout = new javax.swing.GroupLayout(jPanelPlate);
        jPanelPlate.setLayout(jPanelPlateLayout);
        jPanelPlateLayout.setHorizontalGroup(
            jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlateLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPrice1)
                    .addComponent(jLblPrice2)
                    .addComponent(jLblPrice3))
                .addGap(22, 22, 22))
        );
        jPanelPlateLayout.setVerticalGroup(
            jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLblPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLblPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPlateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLblPrice3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelReceipt.setBackground(new java.awt.Color(204, 204, 255));
        jPanelReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)), "Receipt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 0, 14), new java.awt.Color(255, 255, 51))); // NOI18N

        jLblTotal.setText("Total:");

        jLblServTax.setText("Service Tax:");

        jLblGovTax.setText("Gov. Tax:");

        jLblAmount.setText("Total Amount Due:");

        jTxtTotal.setEditable(false);
        jTxtTotal.setText("RM0.0");

        jTxtServTax.setEditable(false);
        jTxtServTax.setText("RM1.50");

        jTxtGovTax.setEditable(false);
        jTxtGovTax.setText("RM1.79");

        jTxtAmount.setEditable(false);
        jTxtAmount.setText("RM0.0");

        javax.swing.GroupLayout jPanelReceiptLayout = new javax.swing.GroupLayout(jPanelReceipt);
        jPanelReceipt.setLayout(jPanelReceiptLayout);
        jPanelReceiptLayout.setHorizontalGroup(
            jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelReceiptLayout.createSequentialGroup()
                        .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblAmount)
                            .addComponent(jLblGovTax))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtGovTax)
                            .addComponent(jTxtAmount)))
                    .addGroup(jPanelReceiptLayout.createSequentialGroup()
                        .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTotal)
                            .addComponent(jLblServTax))
                        .addGap(57, 57, 57)
                        .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtServTax, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanelReceiptLayout.setVerticalGroup(
            jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTotal)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblServTax)
                    .addComponent(jTxtServTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblGovTax)
                    .addComponent(jTxtGovTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAmount)
                    .addComponent(jTxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLblQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblQty.setText("Enter Quantity:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jBtnCalc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnCalc.setText("Calculate");
        jBtnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcActionPerformed(evt);
            }
        });

        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblName)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnClose)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLblName)
                .addGap(18, 18, 18)
                .addComponent(jPanelPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblQty)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCalc))
                .addGap(18, 18, 18)
                .addComponent(jPanelReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnClose)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        this.toBack();
        setVisible(false);
        new WelcomeForm().toFront();
        new WelcomeForm().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcActionPerformed
        double price = 0, total, tax1 = 1.5, tax2 = 1.79, amount;
        int qty = Integer.parseInt(jSpinner1.getValue().toString());
        
        if (jRadioButton1.isSelected())
            price = 29.9;
        else if (jRadioButton2.isSelected())
            price = 34.0;
        else if (jRadioButton3.isSelected())
            price = 32.9;
        else
            JOptionPane.showMessageDialog(null, "Select 1 main dish");
        
        if(jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected())
        {
            total = price * qty;
            amount = total + tax1 + tax2;
            jTxtTotal.setText("RM"+String.format("%.2f",total));
            jTxtAmount.setText("RM"+String.format("%.2f",amount));
        }
    }//GEN-LAST:event_jBtnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCalc;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JLabel jLblAmount;
    private javax.swing.JLabel jLblGovTax;
    private javax.swing.JLabel jLblName;
    private javax.swing.JLabel jLblPrice1;
    private javax.swing.JLabel jLblPrice2;
    private javax.swing.JLabel jLblPrice3;
    private javax.swing.JLabel jLblQty;
    private javax.swing.JLabel jLblServTax;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JPanel jPanelPlate;
    private javax.swing.JPanel jPanelReceipt;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTxtAmount;
    private javax.swing.JTextField jTxtGovTax;
    private javax.swing.JTextField jTxtServTax;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
